version: '2'
services:
    prototipo_rio_doce-app:
        image: prototipo_rio_doce
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://prototipo_rio_doce-mysql:3306/prototipo_rio_doce?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    prototipo_rio_doce-mysql:
        extends:
            file: mysql.yml
            service: prototipo_rio_doce-mysql
